name: scrape-and-update
on:
  schedule:
    - cron: '0 21 * * *' # 매일 새벽 6시 자동 실행
  workflow_dispatch:
    inputs:
      store_url:
        description: '스크래핑할 구글 맵 주소'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        env:
          GOOGLE_COOKIES: ${{ secrets.GOOGLE_COOKIES }}
          GOOGLE_MAPS_URL: ${{ github.event.inputs.store_url }}
        run: python scraper/scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/data/reviews.json
          git commit -m "Update reviews data" || exit 0
          git push
